D8CORE-4778: adding underline hovers to splash links
SU-SWS/stanford_profile_helper pull request #244
Opened 2023-06-02 18:15 UTC by jenbreese

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- D8CORE-4778](https://stanfordits.atlassian.net/browse/D8CORE-4778)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-06-09 18:37 UTC, jdwjdwjdw reviewed
This looks good A11y-wise, but do you think we should we update this to match the other mailto link underlines? [Those have](https://amptesting-test.sites.stanford.edu/interior-page/wysiwyg/test-mailto-links) the underline appearing as the default state, not just on hover.

2023-06-09 19:02 UTC, jenbreese commented
@jdwjdwjdw I'm not sure.  @cjwest Does the underline on the splash text need to be on hover or a constant? I did it as an on hover. But Jacob points out that the other mailto are always underlined and the color changes on hover.  thanks!

2023-06-09 20:12 UTC, cjwest commented
Good question, @jenbreese ! 
My understanding of this has changed over time. I agree with @jdwjdwjdw's point. Here's what the standard says:


To meet WCAG [1.4.1: Use of Color](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color) from [Technique G183](https://www.w3.org/WAI/WCAG21/Techniques/general/G183)

>  underlines are recommended for links in blocks of text.

2023-06-26 21:05 UTC, pookmish approved these changes

2023-06-26 21:05 UTC, pookmish requested changes
Actually, instead of ADDing more css, let's remove the css that this PR is overridding.

2023-06-28 16:20 UTC, jenbreese commented
@pookmish I looked and the `text-decoration:none` comes from Decanter in the @types mixin: core/src/scss/utilities/mixins/typography/_types.scss

That mixin is used on these pages. The headings and the card would like have pretty big impact. It is safer to override rather than remove it in Decanter. I'm concerned it will have trickle effects that I would have to have other teammates agree on.  

**Where the mixin is used:**
decanter/core/src/scss/components/date-stacked/_date-stacked.scss
decanter/core/src/scss/elements/typography/_typography.scss - all headings
decanter/core/src/scss/utilities/mixins/card/_card.scss - on the super headline span
decanter/core/src/scss/utilities/mixins/typography/_font-splash.scss

2023-06-28 16:42 UTC, pookmish commented
Then this issue should really be resolved in decanter. Basically we should never do a `text-decoration: none` without re-setting the decoration on hover. There always needs to be a visual, non-color indicator for hover/focus. all that would really need to be done is add this code block to the `@mixin types`
```    &:hover,
    &:focus {
      text-decoration: underline;
    }```
    
These really should be any link in the affected elements you mentioned. The date stacked doesn't contain any links. The super headline doesn't contain any links. the heading should or already do have an underline if they are a link.

2023-06-28 16:43 UTC, pookmish commented
What it should look like 
![image](https://github.com/SU-SWS/stanford_profile_helper/assets/7185045/ab04fa92-4070-49c8-be28-a49be7508a1e)

2023-06-28 18:16 UTC, jenbreese commented
Ok. That all makes sense. I will create that PR change for Decanter. 

For the splash text, having the underline on hover will solve the original problem in the Jira, correct @cjwest?

2023-06-28 18:36 UTC, cjwest commented
@jenbreese 
We want to treat mailto links just like other links: They are always underlined and the color changes on hover.

2023-08-10 17:33 UTC, pookmish commented
This still needs work.

2025-04-14 16:24 UTC, closed without merging

2025-04-14 16:25 UTC, jenbreese commented
The ticket was marked as done. I'm closing this PR since it is so old and out dated.